server:
  port: 8080
spring:
  application:
    name: ratelimitersample
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的数据脚本
  redis:
    host: 192.168.0.135
    port: 6379
    password: foobared
    timeout: 2000
    pool:
      maxIdle: 300
      minIdle: 100
      max-wait: -1
      max-active: 600
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE                                                        
eureka:
  client:
    healthcheck: 
      enabled: true
    serviceUrl:
      defaultZone: http://192.168.0.118:8761/eureka/
  instance:
    app-group-name: product
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    

  